axis_linear:
  x: 1 # Left thumb stick vertical
  y: 0 # Left thumb stick horizontal
scale_linear:
  x: 1.5
  y: 1.5
scale_linear_turbo:
  x: 3.5
  y: 3.5
axis_angular:
  yaw: 3 # Right thumb stick horizontal
scale_angular:
  yaw: 0.4
scale_angular_turbo:
  yaw: 1.5
enable_button: 4 # Left bumper
enable_turbo_button: 5 # Right bumper
